org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
kotlin.code.style=official
paperVersion=26.2.build.112-stable
paperMinecraftVersion=26.2
paperBuild=112
paperDownloadUrl=https://fill-data.papermc.io/v1/objects/bd3a58cf96874e5ea6643f5f6fe9b4f5bf9e34b795fa078c2f0ee8b98b2f907e/paper-26.2-112.jar
paperDownloadSha256=bd3a58cf96874e5ea6643f5f6fe9b4f5bf9e34b795fa078c2f0ee8b98b2f907e
